forecastle:
  namespace: forecastle
  image:
    name: stakater/forecastle
    tag: v1.0.157
  deployment:
    replicas: 2
    revisionHistoryLimit: 5
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 10001
      fsGroup: 10001
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      runAsNonRoot: true
      runAsUser: 10002
      runAsGroup: 10002
      readOnlyRootFilesystem: true
      capabilities:
       drop:
         - ALL
      privileged: false
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
    resources:
      requests:
        cpu: 100m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 32Mi
  networkPolicy:
    enabled: true
  config:
    title: my-title
    instanceName: my-instance
    crdEnabled: true
    namespaceSelector:
      matchNames:
        - forecastle
