apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra.metrics-server
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: infra/metrics-server/overlay/charts/inflator/REGION
    repoURL: https://github.com/rodrigo14miguel/argocd-bootstrap-demo.git
    targetRevision: BRANCH
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true