---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
spec:
  template:
    spec:
      containers:
      - name: metrics-server
        resources:
          requests:
            cpu: 50m
            memory: 100Mi